services:
  db:
    image: postgres
    restart: always
    container_name: my-soup-postgres
    environment:
      POSTGRES_USER: eddy3o
      POSTGRES_PASSWORD: 228097.And
      POSTGRES_DB: soup
  redis: 
    image: redis:7
    restart: always
    container_name: soup-jwt-redis
    ports: 
      - "6379:6379"

